name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish from Dev
    runs-on: windows-latest
    
    steps:

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.0.0
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowSourceInstance: ${{ secrets.SN_TEST_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}

  test:
    needs: build
    name: Run ATF in Test
    runs-on: windows-latest
    # if: ${{ github.event_name == 'pull_request'}}
    
    steps:
      - name: ServiceNow CI/CD Run ATF Test Suite
        uses: ServiceNow/sncicd-tests-run@1.0.0
        with:
          browserName: 'Chrome'
          browserVersion: '8'
          osName: 'Windows'
          osVersion: '10'
          testSuiteSysId: ${{ secrets.SN_ATFTESTSUITE_SYSID }}
        env:
          snowUsername: ${{ secrets.SN_USERNAME }}
          snowPassword: ${{ secrets.SN_PASSWORD }}
          snowInstallInstance: ${{ secrets.SN_TEST_INSTANCE }}
